name: GuiGive
version: ${project.version}
main: net.kunmc.lab.guigive.GuiGive
api-version: 1.15

commands:
  gives:
    usage: |-
      /gives add <name> - インベントリGUIを開く 閉じると<name>インデックスの更新と設定ファイルの更新が行われる
      /gives apply <name> <player> - <name>に設定されたアイテムを<player>へ配布
      /gives item <player> - インベントリGUIを開く 閉じると即座にアイテムを<player>へ配布
      /gives default-item <name> - リスポーン時に配られるインベントリを指定
      /gives remove <name> - インベントリの設定ファイルを削除